import { v4 as uuid } from "uuid";

export const UsersData = [
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "1-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
    { id: uuid(), surName: "Skriabin", name: "Aleksei", position: "frontend developer", companyId: "2-company" },
];